type: JWT Authentication
description: "Отправляем токен пользователя в теле POST-запроса, в параметре \"params.meta.Authorization\""
describedBy:
    responses:
        200:
            body:
                application/json:
                    example: !include example/unauthorized-response.json
